spring.datasource.url=jdbc:mysql://localhost:3306/leave_db
spring.datasource.username=leavemanagement_db
spring.datasource.password=leavemanagement@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
